#!/usr/bin/env bash

set -euxo pipefail

export BUILDKIT_PROGRESS=plain
export PROGRESS_NO_TRUNC=1

DOCKER_REPO="zstd_builder"
DOCKER_IMAGE_NAME_SAFE="${DOCKER_REPO//\//-}"
DOCKER_CONTAINER_NAME="${DOCKER_IMAGE_NAME_SAFE}-$(date -u "+%Y-%m-%d_%H-%M-%S_%3NZ")"

DOCKER_BASE_IMAGE="quay.io/pypa/manylinux2014_x86_64"
# DOCKER_BASE_IMAGE="ubuntu:24.04"

USER="user"
GROUP="user"

docker build \
  --tag="${DOCKER_IMAGE_NAME_SAFE}" \
  --network=host \
  --build-arg="DOCKER_BASE_IMAGE=${DOCKER_BASE_IMAGE}" \
  --build-arg="UID=$(id -u)" \
  --build-arg="GID=$(id -g)" \
  --build-arg="USER=${USER}" \
  --build-arg="GROUP=${GROUP}" \
  .

mkdir -p .build .cache/ccache .opt .out

docker run -it --rm \
  --init \
  --name="${DOCKER_CONTAINER_NAME}" \
  --hostname="${DOCKER_IMAGE_NAME_SAFE}" \
  --add-host="${DOCKER_IMAGE_NAME_SAFE}:127.0.1.1" \
  --user="$(id -u):$(id -g)" \
  --volume="$(pwd):/workdir" \
  --volume="$(pwd)/.opt:/opt/zstd" \
  --volume="$(pwd)/.cache/ccache:/cache/ccache" \
  --workdir="/workdir" \
  --env="UID=$(id -u)" \
  --env="GID=$(id -g)" \
  --env="USER=${USER}" \
  --env="GROUP=${GROUP}" \
  --env="PS1=\${USER}@\${HOST}" \
  --env="TZ=Etc/UTC" \
  --env="LANG=C.UTF-8" \
  --ulimit core=0 \
  "$DOCKER_IMAGE_NAME_SAFE" \
  bash ./scripts/main
